# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
    server.vm.box = "bento/ubuntu-20.04"
    server.vm.network "private_network",ip:"192.168.5.2"
    server.vm.hostname = "barp-server"
    server.vm.define "barp-server"
    server.vm.synced_folder "../", "/home/vagrant/barp"
    server.vm.provision :shell, path: "server-bootstrap.sh"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "4"
    end
  end
  config.vm.define "client" do |client|
    client.vm.box = "bento/ubuntu-20.04"
    client.vm.network "private_network",ip:"192.168.5.3"
    client.vm.hostname = "barp-client"
    client.vm.define "barp-client"
    client.vm.synced_folder "../", "/home/vagrant/barp"
    client.vm.provision :shell, path: "client-bootstrap.sh"
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "4"
    end
  end
end
